In [44]:
import numpy as np

In [ ]:
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[4.9e-324 1.5e-323]
 [1.5e-323 4.9e-324]]


In [ ]:
ones_array = np.ones((4, 2))
print("All Ones Array:\n", ones_array)

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("Filled Array:\n", filled_array)

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("Zeros Like Array:\n", zeros_like_array)

Zeros Like Array:
 [[0 0 0]
 [0 0 0]]


In [ ]:
ones_like_array = np.ones_like(reference_array)
print("Ones Like Array:\n", ones_like_array)

Ones Like Array:
 [[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array:\n", numpy_array)

Converted NumPy Array:
 [1 2 3 4]


In [ ]:
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\Random Array Mean:", mean_value)

\Random Array Mean: 0.5005394963855504


In [ ]:
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Min value:", min_value, "Max value:", max_value)

Min value: 0.004998289831889768 Max value: 0.9987129218787908


In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero Array with 5th element as 1:\n", zero_array)

Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on border and 0 inside:\n", border_array)

2D Array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [55]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
add_xy = x + y
print("Addition of x and y:\n", add_xy)

Addition of x and y:
 [[ 6  8]
 [10 13]]


In [ ]:
sub_xy = x - y
print("Subtraction of x and y:\n", sub_xy)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [ ]:
mult_x = x * 3
print("Multiplication of x with 3:\n", mult_x)

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]


In [ ]:
square_x = np.square(x)
print("Square of each element in x:\n", square_x)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [ ]:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [ ]:
concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n", concat_xy_row)

# Concatenate v and w along columns
concat_vw_col = np.vstack((v, w))  # Using vstack (same as np.concatenate with axis=0)
print("Concatenation of v and w along columns:\n", concat_vw_col)

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]


In [ ]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error while concatenating x and v:", e)

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# 1.
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1) = I:\n", np.round(identity_matrix, decimals=5))

# 2.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))  

# 3. 
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)
print("(AB)^T == B^T A^T?", np.array_equal(AB_T, BT_AT)) 

A * A^(-1) = I:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T? True


In [ ]:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Representing as AX = B
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficients matrix
B_matrix = np.array([-1, -3, 9])  # Constant matrix

# Solving using inverse method: X = A⁻¹ * B
A_inv = np.linalg.inv(A_matrix)  # Compute inverse of A
X = np.dot(A_inv, B_matrix)  # Solution for X
print("\nSolution using Inverse Method:\n", X)

# Alternative approach: Using np.linalg.solve()
X_solve = np.linalg.solve(A_matrix, B_matrix)
print("\nSolution using np.linalg.solve():\n", X_solve)


Solution using Inverse Method:
 [ 2.  1. -2.]

Solution using np.linalg.solve():
 [ 2.  1. -2.]


In [68]:
import time

In [ ]:
# Using Python lists
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000, 2_000_000)]
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(1_000_000)]  # Element-wise addition
end_time = time.time()
print(f"Element-wise addition using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays
np_array1 = np.arange(1_000_000)
np_array2 = np.arange(1_000_000, 2_000_000)
start_time = time.time()
result_np = np_array1 + np_array2  # Element-wise addition
end_time = time.time()
print(f"Element-wise addition using NumPy arrays took: {end_time - start_time:.6f} seconds")

Element-wise addition using Python lists took: 0.142377 seconds
Element-wise addition using NumPy arrays took: 0.007966 seconds


In [ ]:
# Using Python lists
start_time = time.time()
result_list_mult = [list1[i] * list2[i] for i in range(1_000_000)]  # Element-wise multiplication
end_time = time.time()
print(f"Element-wise multiplication using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
result_np_mult = np_array1 * np_array2  # Element-wise multiplication
end_time = time.time()
print(f"Element-wise multiplication using NumPy arrays took: {end_time - start_time:.6f} seconds")

Element-wise multiplication using Python lists took: 0.185417 seconds
Element-wise multiplication using NumPy arrays took: 0.008147 seconds


In [ ]:
# Using Python lists
start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(1_000_000)])  # Dot product
end_time = time.time()
print(f"Dot product using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays
start_time = time.time()
dot_product_np = np.dot(np_array1, np_array2)  # Dot product
end_time = time.time()
print(f"Dot product using NumPy arrays took: {end_time - start_time:.6f} seconds")

Dot product using Python lists took: 0.256972 seconds
Dot product using NumPy arrays took: 0.002123 seconds


In [ ]:
# Using Python lists (1000x1000 matrices)
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]
start_time = time.time()
result_matrix_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]  # Matrix multiplication
end_time = time.time()
print(f"Matrix multiplication using Python lists took: {end_time - start_time:.6f} seconds")

# Using NumPy arrays (1000x1000 matrices)
np_matrix1 = np.random.rand(1000, 1000)
np_matrix2 = np.random.rand(1000, 1000)
start_time = time.time()
result_matrix_np = np.dot(np_matrix1, np_matrix2)  # Matrix multiplication
end_time = time.time()
print(f"Matrix multiplication using NumPy arrays took: {end_time - start_time:.6f} seconds")

Matrix multiplication using Python lists took: 185.876719 seconds
Matrix multiplication using NumPy arrays took: 0.111267 seconds
